export default {
  'SET_REPOSITORIES': 'SET_REPOSITORIES',
  'SET_REPOSITORIES_LOADING': 'SET_REPOSITORIES_LOADING',
  'SET_REPOSITORIES_FAILED': 'SET_REPOSITORIES,_FAILED',
  'CLEAR_REPOSITORIES': 'CLEAR_REPOSITORIES',
}