export default {
  'SET_RESULTS': 'SET_RESULTS',
  'SET_LAST_SEARCH': 'SET_LAST_SEARCH',
  'SET_SEARCH_FAIL': 'SET_SEARCH_FAIL',
  'SET_SEARCH_NEXT_PAGE_FAIL': 'SET_SEARCH_NEXT_PAGE_FAIL',
  'SET_SEARCH_LOADING': 'SET_SEARCH_LOADING',
  'SET_SEARCH_NEXT_PAGE_LOADING': 'SET_SEARCH_NEXT_PAGE_LOADING',
  'CLEAR_SEARCH': 'CLEAR_SEARCH',
}